### PR TITLE
Allow ghc-bignum-1.3 (GHC 9.4)

### PR DESCRIPTION
**Pull request by ysangkok**
Tested using

    cabal test -w ghc-9.4.1

### CODE REVIEW

**Review by RyanGlScott — APPROVED** [review]

**Comment by RyanGlScott** [comment]
Thanks. I've applied a corresponding Hackage revision [here](https://hackage.haskell.org/package/discrimination-0.5/revisions/).

**Comment by phadej** [comment]
I was hesitating merging this, as CI was not updated, so there is no visible evidence it works.

... and CI still have to be updated.

**Comment by RyanGlScott** [comment]
My apologies, I didn't realize that you had an objection to merging this. (For what it's worth, I tested this locally using GHC 9.4, which builds and tests without issue.)

Perhaps we should look into making a new Hackage release of `haskell-ci` that supports GHC 9.4? That way, it's easier for contributors to update the CI themselves.

**Comment by phadej** [comment]
> Perhaps we should look into making a new Hackage release of `haskell-ci` that supports GHC 9.4?

As soon as there is "usable" `cabal-install` release.

**Pull request merged**
